/*

문제링크 : https://school.programmers.co.kr/learn/courses/30/lessons/131532?language=oracle
문제 이름 : 년, 월, 성별 별 상품 구매 회원 수 구하기
난이도 : LV4
*/
SELECT
    TO_NUMBER(EXTRACT(YEAR FROM A.SALES_DATE)) YEAR,
    TO_NUMBER(EXTRACT(MONTH FROM A.SALES_DATE)) MONTH,
    TO_NUMBER(B.GENDER) GENDER,
    COUNT(DISTINCT(B.USER_ID)) USERS
FROM 
    ONLINE_SALE A,
    USER_INFO B
WHERE 1=1
    AND A.USER_ID = B.USER_ID
    AND B.GENDER IS NOT NULL
GROUP BY
    EXTRACT(YEAR FROM A.SALES_DATE), EXTRACT(MONTH FROM A.SALES_DATE), B.GENDER
ORDER BY
    YEAR ASC, MONTH ASC, GENDER ASC

;
